tasks:
  - init: |
      cd 'Refactoring - First Example/before'
      yarn install
      yarn build 
      cd 'Refactoring - First Example/after'
      yarn install
      yarn build 
  - command: |
      # must be in command, not init, not before due to only /workspace is persisted
      # must all in oneline or apt-get install will break the installation zz-_28-_y22-0716-2216
      sudo apt-get -qq update && sudo apt-get -qq install -y python3 python3-pip libxext6 libxrender1 libxtst6 libfreetype6 libxi6 && pip3 install projector-installer && mkdir -p ~/.projector/configs && projector ide autoinstall --config-name Idea --ide-name "IntelliJ IDEA Ultimate 2022.1.2"
      cd 'Refactoring - First Example'
      code .
